name: snake-on-contribution-graph

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update my contribution graph
    
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: generate snake game
        id: generate-snake
        uses: Platane/snk@v2
        with:
          github_user_name: iamwatchdogs
          outputs: |
           dark.svg?palette=github-dark&color_snake=blue
           light.svg?color_snake=#7845ab
           ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

            
      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/github-contribution-grid-snake.svg
          test -f dist/github-contribution-grid-snake-dark.svg
          test -f dist/github-contribution-grid-snake.gif

      - name: Using GitHub Pages to deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
