name: snake-on-contribution-graph

on:
  push:
    paths:
      - '**.yml'
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update my contribution graph
    
    runs-on: ubuntu-latest
    steps:
    
      - name: checking out the repo
        uses: actions/checkout@v2
             
      - name: generating snake
        uses: Platane/snk@v2.2.1
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dark.svg?palette=github-dark&color_snake=blue
            light.svg?color_snake=#7845ab
            ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
       
      - name: ensure the generated file exists
        run: |
          ls dist
          ls -a
          # test -f dist/github-contribution-grid-snake.svg
          # test -f dist/github-contribution-grid-snake-dark.svg
          # test -f dist/github-contribution-grid-snake.gif
          
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
